### ISSUE TITLE
Integration for public API

### ISSUE THREAD

**Issue by nicosammito** [Uroria/Backend#1]
We should discuss if we provide a public API either over REST or some other event based system like Webhook or WS for developers to integrate our server into clients or stats pages. This should be than integrated into the backend logic.

**Comment by julian-siebert** [comment]
I would like to integrate such API in a separate application, because this app is not able to scale in any way

**Comment by nicosammito** [comment]
> I would like to integrate such API in a separate application, because this app is not able to scale in any way

Okay yep, this makes sense to me. Maybe we should also then discuss if want to develop a developer dashboard in the future. Let's keep this issue for the time and come back later to discuss this project.

**Comment by julian-siebert** [comment]
> > I would like to integrate such API in a separate application, because this app is not able to scale in any way
> 
> Okay yep, this makes sense to me. Maybe we should also then discuss if want to develop a developer dashboard in the future. Let's keep this issue for the time and come back later to discuss this project.

Well for testing environments something like this would be pretty essential. If we could create Test-Servers with a separate database and more, we would have a nice method of testing for game-developers

**Comment by nicosammito** [comment]
> > > I would like to integrate such API in a separate application, because this app is not able to scale in any way
> > 
> > 
> > Okay yep, this makes sense to me. Maybe we should also then discuss if want to develop a developer dashboard in the future. Let's keep this issue for the time and come back later to discuss this project.
> 
> Well for testing environments something like this would be pretty essential. If we could create Test-Servers with a separate database and more, we would have a nice method of testing for game-developers

a testing env makes sense but is hardly implementable. Because we can't work with live data in this env. So we should maybe just ignore a dev env for the moment and just create a hook based api which you can play around with.

**Comment by julian-siebert** [comment]
In terms of productivity, that is not smart. Every Game-Developer needs an independent testing-environment to test *no shit* their games. Creating more databases or starting new environments is not that hard. We just need a great Web UI for the developers to use, since we are not allowed to give access to the internal servers due to data privacy terms of Zyonic, which prohibits access for normal users.

**Comment by nicosammito** [comment]
> In terms of productivity, that is not smart. Every Game-Developer needs an independent testing-environment to test _no shit_ their games. Creating more databases or starting new environments is not that hard. We just need a great Web UI for the developers to use, since we are not allowed to give access to the internal servers due to data privacy terms of Zyonic, which prohibits access for normal users.

Okay you completely misunderstood me. I'm not talking about Game-Devs or our private gitlab or whatever. I am talking about a public API like Hypixel's to give independent developers the option to develop for example apps for clients like Badline or some other clients. 

This API has only the purpose to simply deliver stored data like stats to developers outside of the team. And for this particular purpose it doesn't make sense to create a testing env for them with fake data. They just can play around with the live data like other API's e.g. discord developer api or any other does it

**Comment by julian-siebert** [comment]
I understood everything. A public API is not planned for near future and has lowest priority.

**Comment by nicosammito** [comment]
> I understood everything. A public API is not planned for near future and has lowest priority.

Yep okay 👍🏻
